config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/creatures", to: "creatures#index"
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creature.rb
class Creature < ApplicationRecord
  belongs_to :creatures, polymorphic: true
end

app/models/fish.rb
class Fish < ApplicationRecord
  has_one :creature, as: :creatures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  def index
    @creatures = Creature.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/creatures/index.html.slim
h1 Bugs & Fish

table
  thead
    tr
      th Name
      th Price

  tbody
    - @creatures.each do |creature|
      tr
        td = creature.name
        td = creature.price

app/views/home/index.html.slim
h1 AC:NL Companion

ul
  li = link_to "Bugs & Fish", creatures_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title AC:NL Companion
    = csrf_meta_tags
    
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"

  body
    .menu
      ul
        li = link_to "Home", root_path
        - if admin_user_signed_in?
          li = link_to "Admin", admin_root_path

    .container
      = yield